# this is either runnable from the projects root
# - with Hugo's webserver by `hugo server`
# - or by compiling `hugo --cleanDestinationDir` and `npx http-server . -p 1313`
baseURL: "http://localhost:1313/public/"
canonifyURLs: true
relativeURLs: false
uglyurls: true

languageCode: "de-DE"
metaDataFormat: "yaml"

theme:
  - "relearn"

outputs:
  home:
    - HTML
    - PRINT
  section:
    - HTML
    - PRINT
  page:
    - HTML
    - PRINT
